Repository knative/client-pkg, pull requests merged in 2022-04, with the labels that each got.

#27 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#34 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#32 Adding code of conduct to reference knative/community's CoC
  CODE-OF-CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: lgtm, approved, size/XS

#33 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: lgtm, size/XL, approved

#37 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
