Repository knative/client-pkg, pull requests merged in 2022-07, with the labels that each got.

#50 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#52 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#54 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#53 🧹 remove defunct variable DISABLE_MD_LINTING
  test/presubmit-tests.sh
Labels: lgtm, approved, size/XS, kind/cleanup

#55 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#51 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/go.mod
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/pkg/changeset/doc.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/logging/logkey/constants.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/modules.txt
Labels: lgtm, size/L, approved
