Repository knative/client-pkg, pull requests merged in 2023-10, with the labels that each got.

#120 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#121 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#124 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#125 Remove deprecated Serving API v1alpha1
  pkg/kn/commands/types.go
  pkg/kn/commands/types_test.go
  pkg/serving/v1beta1/client.go
  pkg/serving/v1beta1/client_mock.go
  pkg/serving/v1beta1/client_mock_test.go
  pkg/serving/v1beta1/client_test.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1beta1/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1beta1/domainmapping.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1beta1/fake/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1beta1/fake/fake_domainmapping.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1beta1/fake/fake_serving_client.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1beta1/generated_expansion.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1beta1/serving_client.go
  vendor/modules.txt
Labels: lgtm, size/XL, approved

#126 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_lifecycle.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#127 Add plugin context sharing types
  pkg/plugin/context_sharing_types.go
Labels: lgtm, approved, size/M

#128 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/domainmapping_lifecycle.go
  vendor/knative.dev/serving/pkg/testing/v1/route.go
  vendor/modules.txt
Labels: lgtm, approved, size/M
