Repository knative/client-pkg, pull requests merged in 2023-01, with the labels that each got.

#81 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#82 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#79 Move code being used by func from client
  pkg/kn-source-pkg/test/e2e/basic_workflow_test.go
  pkg/kn-source-pkg/test/e2e/common.go
  pkg/kn-source-pkg/test/e2e/kn_plugin.go
  pkg/kn/commands/namespaced_test.go
  pkg/kn/commands/types_test.go
  pkg/kn/flags/podspec_helper_test.go
  pkg/serving/v1/gitops_test.go
  pkg/util/test/capture_output.go
  pkg/util/test/cli.go
  pkg/util/test/flags.go
  pkg/util/test/integration.go
  pkg/util/test/result_collector.go
  pkg/util/test/service.go
  pkg/util/test/utils.go
Labels: lgtm, size/L, approved, kind/enhancement

#78 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/sql/v2/parser/expression_visitor.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/utils/casting.go
  vendor/github.com/cloudevents/sdk-go/v2/alias.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/abuse_protection.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_lifecycle.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_validation.go
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_defaults.go
  vendor/knative.dev/serving/pkg/testing/v1/service.go
  vendor/modules.txt
Labels: lgtm, size/L, approved
