Repository knative/client-pkg, pull requests merged in 2024-01, with the labels that each got.

#136 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#133 add clotributor link to readme
  README.md
Labels: lgtm, approved, size/XS

#140 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#141 updated deps again
  go.mod
Labels: lgtm, approved, size/XS

#142 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_lifecycle.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#143 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#144 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#145 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M
