Repository knative/client-pkg, pull requests merged in 2024-03, with the labels that each got.

#155 :broom: Clean up the `kn` sub-package
  pkg/commands/describe.go
  pkg/commands/describe_test.go
  pkg/commands/flags/listprint.go
  pkg/commands/flags/listprint_test.go
  pkg/commands/flags/sink.go
  pkg/commands/flags/sink_test.go
  pkg/commands/human_readable_flags.go
  pkg/commands/human_readable_flags_test.go
  pkg/commands/namespaced.go
  pkg/commands/namespaced_test.go
  pkg/commands/testing_helper.go
  pkg/commands/types.go
  pkg/commands/types_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/types.go
  pkg/flags/bool.go
  pkg/flags/bool_test.go
  pkg/flags/podspec_helper.go
  pkg/flags/podspec_helper_test.go
  pkg/kn-source-pkg/pkg/factories/flags_factory.go
  pkg/kn-source-pkg/pkg/factories/kn_source_factory.go
  pkg/kn-source-pkg/pkg/factories/kn_source_factory_test.go
  pkg/kn-source-pkg/pkg/types/structs.go
  pkg/kn-source-pkg/pkg/types/structs_test.go
  pkg/kn/plugin/types.go
  pkg/serving/config_changes.go
Labels: lgtm, size/L, approved, kind/cleanup

#158 Enable Codecov auto target config
  .codecov.yaml
Labels: lgtm, approved, size/XS

#153 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#162 :lady_beetle: Fix the hang of the spinner and progress bar on stop
  pkg/output/tui/progress.go
  pkg/output/tui/spinner.go
Labels: lgtm, approved, size/M, kind/bug

#164 :bug: Bubbletea initialization error handling
  go.mod
  pkg/output/logging/context.go
  pkg/output/term/io.go
  pkg/output/tui/bubbletea964.go
  pkg/output/tui/bubbletea964_test.go
  pkg/output/tui/progress.go
  pkg/output/tui/progress_test.go
  pkg/output/tui/spinner.go
  pkg/output/tui/spinner_test.go
Labels: lgtm, size/L, approved, kind/bug

#167 :bug: Override localereader to use master branch version
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/mattn/go-localereader/LICENSE
  third_party/VENDOR-LICENSE/knative.dev/client-pkg/pkg/LICENSE
  vendor/github.com/mattn/go-localereader/LICENSE
  vendor/modules.txt
Labels: lgtm, approved, size/M, kind/bug

#156 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/golang/protobuf/ptypes/any.go
  vendor/github.com/prometheus/common/expfmt/expfmt.go
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/resolver_wrapper.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#171 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review
